### PR TITLE
Fix FILE* resource leak in agread() wrapper 

### PR DESCRIPTION
**Pull request by nehaljwani**
Resolves https://github.com/pygraphviz/pygraphviz/issues/213

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Review by dschult — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
Thanks @nehaljwani !

**Comment by rossbar** [comment]
Ack, I just noticed that the changes here modify the generated `graphviz_wrap.c` file directly... this means that the changes would be overridden/lost if/when the C code is regenerated w/ SWIG.

In other words, the changes to `graphviz_wrap.c` should be instead moved to `graphviz.i`. Unfortunately the mapping from SWIG definition to C-code is not immediately clear to me... @Nagael , any chance there is a quick fix here? IYO is there a straightforward way to modify `graphviz.i` to result in the changes we see in `graphviz_wrap.c` here in this diff?

**Comment by dschult** [comment]
I'm not sure, and I don't have a setup to test this, but it looks like the following might work:

line 18: add the dup() around fd
```
        $1 = fdopen(dup(fd), mode);
```

line 94-96:   add a line to fclose(arg1);
```
%exception agread {
  $action
  fclose(arg1);               // added line
  if (!result) {
```

**Comment by rossbar** [comment]
Yeah that was my first thought as well... unfortunately the first line is in a templated function, so it affects two wrapped functions - one of which then causes an infinite hang when running the test suite.

**Comment by Nagael** [comment]
Hi,
I have a proposition, which I described in #432, and you can see it [in this commit](https://github.com/Nagael/pygraphviz/tree/agread-fix-to-swig) . It passes all tests on my setup, but I have no Windows system to test.
Good luck !

**Pull request merged**
