### PR TITLE
Fix gvRenderData bytes output

### PR DESCRIPTION
**Pull request by Nagael**
This PR fixes the `AGraph._draw(format='png')` case. The PNG format can contain NULL bytes, so this call could result in an assertion error: 
```
File "[...]/pygraphviz/agraph.py", line 1729, in _draw
    assert len(dot_string) == length
AssertionError
```
This fix correctly uses SWIG's `%cstring_output_allocate_size(parm, szparm, release)` instead of `%cstring_output_allocate(parm, release)` (as explained in 11.3.4 of https://www.swig.org/Doc4.0/Library.html)

Unfortunately my local SWIG installation is 4.0.1, so the regenerated SWIG files are more different than strictly necessary. The first commit is the main one, though.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Thanks @Nagael , this seems good. The one missing piece is a test that illustrates the failure; i.e. something that fails with the current code that passes with this patch. Do you have any example cases where you hit this problem that could be added to the test suite?

**Comment by Nagael** [comment]
Thanks for your answer. I just added a commit with a test that fails on the current version. It asks for the `png` format, and at first I thought that the test should not assume that this format is available. But since other tests also use this format, I removed the check in a second commit. You can use whichever version is more convenient for the project.

**Review by rossbar — APPROVED** [review]
Thanks for this @Nagael . I went ahead and re-generated `graphviz.py` and `graphviz_wrap.c` with SWIG 4.0.2. I'm not too familiar with SWIG, so if you wouldn't mind taking a quick look at the generated `graphviz_wrap.c` code to verify that everything looks as expected that'd be great.

I also went ahead and renamed/added a comment to the test so we have a better idea of what it's designed to catch. If you have any wording/name changes you think would be better, please go ahead and make them. Other than that, this LGTM! We always squash-merge so no need to worry about cleaning up the history.

**Comment by Nagael** [comment]
Thanks @rossbar, everything looks just as expected and works smoothly. Looks good to me too!

**Comment by rossbar** [comment]
Great, then in this goes (the failing CI is a known issue). Thanks again @Nagael !

**Pull request merged**
