### PR TITLE
Windows Manual Installation Fix

### PR DESCRIPTION
**Pull request by Javiolonchelo**
Fixed the manual installation instructions for Windows. I tried to copy-paste into my terminal but produced some errors. I believe there were some extra ".

I skipped the contributing guidelines because this change does not affect funcionality and I won't be working on this project in the near future.

Thanks in advance, I hope this helps :)

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
Looks like this change should also be made on lines 96-97 and 163-164.  
I’m a little surprised that the suggested change works with only two double-quotes.  But the current three double-quotes is clearly wrong. I don’t have a way to test it.

**Comment by pbadeer** [comment]
If this command is meant to work in Powershell on windows, it also needs the line ending characters changed:

```powershell
python -m pip install --use-pep517 ^
              --global-option=build_ext ^
              --global-option="-IC:\Program Files\Graphviz\include" ^
              --global-option="-LC:\Program Files\Graphviz\lib" ^
              pygraphviz
```

**Review by rossbar — COMMENTED** [review]
Thanks for the comments @pbadeer . Would you be able to make changes to the github workflow to use the correct powershell syntax? The relevant section is here:

https://github.com/pygraphviz/pygraphviz/blob/c7c2b272f00baea2fb50de05a731f44ec0c14c92/.github/workflows/test.yml#L189-L198

This is really the only way we have to verify that any of the suggestions actually work.

**Comment by yasu-sh** [comment]
@pbadeer cmd.exe 's the line continuation character is '^' . Not for PowerShell. 
https://devblogs.microsoft.com/scripting/powertip-line-continuation-in-powershell/

Your command seemed to work on cmd.exe, but did not worked since --global-option 

> If this command is meant to work in Powershell on windows, it also needs the line ending characters changed:
> 
> ```powershell
> python -m pip install --use-pep517 ^
>               --global-option=build_ext ^
>               --global-option="-IC:\Program Files\Graphviz\include" ^
>               --global-option="-LC:\Program Files\Graphviz\lib" ^
>               pygraphviz
> ```

When using cmd.exe as @pbadeer says, it was not successful since pep517 option is neglected by --global-options effect.
```Shell Session (console)
PS E:> pip --version
pip 23.2.1 from E:\GitLab\venv\powerpnt\lib\site-packages\pip (python 3.10)
PS E:> cmd
Microsoft Windows [Version 10.0.19045.2846]
(c) Microsoft Corporation. All rights reserved.

E:\>python -m pip install --use-pep517 ^
More?               --global-option=build_ext ^
More?               --global-option="-IC:\Program Files\Graphviz\include" ^
More?               --global-option="-LC:\Program Files\Graphviz\lib" ^
More?               pygraphviz
DEPRECATION: --build-option and --global-option are deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option. 
Collecting pygraphviz
  Using cached pygraphviz-1.11.zip (120 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygraphviz
  **WARNING: Ignoring --global-option when building pygraphviz using PEP 517**
  Building wheel for pygraphviz (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pygraphviz (pyproject.toml) did not run successfully.
```

This case, this works on cmd.exe on the pip version 23.2.1.
```Shell Session (console)
PS E:\PyProjects\powerpnt> cmd
Microsoft Windows [Version 10.0.19045.2846]
(c) Microsoft Corporation. All rights reserved.

E:\PyProjects\powerpnt>python -m pip install --use-pep517 ^
More?               --config-setting="--global-option=build_ext" ^
More?               --config-setting="--global-option=-IC:\Program Files\Graphviz\include" ^
More?               --config-setting="--global-option=-LC:\Program Files\Graphviz\lib" ^
More?               pygraphviz
Collecting pygraphviz
  Using cached pygraphviz-1.11.zip (120 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (pyproject.toml) ... done
  Created wheel for pygraphviz: filename=pygraphviz-1.11-cp310-cp310-win_amd64.whl size=107856 sha256=54d24fece8bfbccdb8237da5f14b186bfbeb8f9c3f5c8cf967ed8e437bf5f5b5
  Stored in directory: c:\users\5001870\appdata\local\pip\cache\wheels\5b\ee\36\f47a0d35664fbe1a2b5a433ae33c6ad636b00bb231f68a9aaa
Successfully built pygraphviz
Installing collected packages: pygraphviz
Successfully installed pygraphviz-1.11
```

**Comment by yasu-sh** [comment]
@rossbar I have coded and made it in successful in installation for windows cmd.exe with @pbadeer methods.

https://github.com/yasu-sh/pygraphviz/actions/runs/6294180873/job/17085663722#step:7:103

[Commit of Github Actions for cmd.exe](https://github.com/pygraphviz/pygraphviz/compare/main...yasu-sh:pygraphviz:%23468_WFforWinCmd) 

```yaml
    # We need ``python -m pip install -U pip`` b/c Windows won't modify running programs.
    # cmd.exe use same env variables with pwsh.
    - name: Install packages
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements/test.txt
        python -m pip install --global-option=build_ext ^
          --global-option="-I%WIN_GRAPHVIZ_DIR%\include" ^
          --global-option="-L%WIN_GRAPHVIZ_DIR%\lib" ^
          .
        python -m pip list
      shell: cmd
```


> Thanks for the comments @pbadeer . Would you be able to make changes to the github workflow to use the correct powershell syntax? The relevant section is here:
> 
> https://github.com/pygraphviz/pygraphviz/blob/c7c2b272f00baea2fb50de05a731f44ec0c14c92/.github/workflows/test.yml#L189-L198
> 
> This is really the only way we have to verify that any of the suggestions actually work.

**Review by rossbar — APPROVED** [review]
Sorry for the delay here - debugging via CI is not the most efficient process. Thanks to @yasu-sh and @GattoPianista for the suggestions - the proposed recipe is now confirmed to work (as indicated by the CI changes) for windows.

Closes #480 #478 #477

**Comment by MridulS** [comment]
Thanks everyone!

**Comment by yasu-sh** [comment]
@rossbar  @MridulS Thanks for your actions for this issue. 
I think there are outstanding item, MacPorts and Chocolatey as I made PR once, for chocolatey, #477. 

Should I made action? or Can I expect somebody in contributors be making actions?
https://github.com/pygraphviz/pygraphviz/pull/479/files#

**Pull request merged**
