### PR TITLE
Fix segfault on attribute changes after layout.

### PR DESCRIPTION
**Pull request by pope1ni**
Simple reproducible crash fixed by this commit:

```
>>> import pygraphviz
>>> G = pygraphviz.agraph.AGraph()
>>> G.layout(prog='dot')
>>> G.graph_attr['label'] = 'ABC'
Segmentation fault (core dumped)
```

This is similar to another segmentation fault related to handle changes that was fixed by 3bfd923.

### CODE REVIEW

**Comment by pope1ni** [comment]
Test failures seem to be unrelated.

**Comment by hagberg** [comment]
Yes, definitely a bug.  If you can see where the problem is please update this.

**Comment by pope1ni** [comment]
@hagberg: I'm not sure what you mean... This PR does fix the bug...

**Comment by pope1ni** [comment]
Thanks!

**Pull request merged**
