### PR TITLE
Auto detect graphviz installation path on ubuntu

### PR DESCRIPTION
**Pull request by mmarkov**
- implemented search for graphviz installation using dpkg
- improve handling of empty strings, now if path not found error message is generated
- added unit tests to cover new functionality
- this pull request addresses installation issues for Ubuntu (reported in #72  and #71 )

### CODE REVIEW

**Comment by hagberg** [comment]
This looks like it should work.  I wonder if there is a simpler solution.  The problem seems to be that the default pkg-config output doesn't include -L/usr/lib - it does if you install into /usr/local/lib, e.g.
$ pkg-config --libs /usr/lib/pkgconfig/libcgraph.pc 
-lcgraph -lcdt
$ pkg-config --libs /usr/local/lib/pkgconfig/libcgraph.pc 
-L/usr/local/lib -lcgraph -lcdt 

Does it solve this problem if we add -L/usr/lib if no path is given?

**Comment by mmarkov** [comment]
@hagberg, I tried install pygraphviz 1.3.1 on clean ubuntu and the challenge is that it installs but doesn't work. As far as I understand to compile pygraphvix SWIG wrapper it is enough to provide only  -lcgraph -lcdt. But as cgraph is abstract library, it doesn't work unless we link with actual implementation (appropriate so or dynlib files). Normally if someone installs graphviz using apt it is installed to /usr/local/lib/graphviz and linker needs this folder to be included into linking path.

Ah, and there is no pkg-config on newly installed ubuntu.

**Comment by hagberg** [comment]
OK - maybe there is more than one issue here?
1) pkg-config is not part of the default ubuntu install - I suggest we require/use pkg-config and note that users need to install this
2) pkg-config doesn't produce -L/usr/lib with the default graphviz install in /usr - maybe that is the way it is supposed to work but pygraphviz doesn't build without that.  

Am I understanding this correctly?

**Comment by mmarkov** [comment]
Yes, you understand it correctly. 
1) Unfortunately, installing pkg-config is not enough - I tried installing it and it doesn't report path to .so files.
2) I tested proposed solution with clean ubuntu and pig-config. Actually -L/usr/lib is not enough because apt installs pygraphviz to -L/usr/lib/pygraphviz and path to this path actually required for proper linking. pygraphviz libraries are not installed in /usr/lib.

**Comment by j9ac9k** [comment]
I can confirm having the same issue, running ubuntu server 15.04 

pip install pygraphviz fails with the following error:

```
  pygraphviz/graphviz_wrap.c:2954:29: fatal error: graphviz/cgraph.h: No such file or directory
   #include "graphviz/cgraph.h"
                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pygraphviz
```

I do have pkg-config installed

**Pull request merged**
