### PR TITLE
Add an image scraper to support pygraphviz in sphinx-gallery

### PR DESCRIPTION
**Pull request by rossbar**
This is a work-in-progress to add a custom image scraper to `pygraphviz` to enable `sphinx-gallery` examples to use `pygraphviz` to generate visualizations for examples. 

This limited example adds an image scraper that will pick up `.png` files generated by `pygraphviz` examples. In principle, this could also be extended to support e.g. `.dot` files as well (if the dependencies make sense).

Note that the docs for `sphinx-gallery` [make explicit](https://sphinx-gallery.github.io/stable/advanced.html#integrate-custom-scrapers-with-sphinx-gallery) that `sphinx-gallery` does not intend to upstream image scrapers from 3rd party projects and instead recommends that image scraper(s) be maintained directly in the relevant library. One annoying consequence of this is that injects `sphinx-gallery` as a default dependency for `pygraphviz`. There are likely ways to mitigate this (e.g. move away from a top-level submodule) but I didn't address it here.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
I haven't thought about this yet, but it looks good in general.  We should update the pygraphviz gallery as well just in case some users aren't looking at the networkx gallery.

**Comment by rossbar** [comment]
>  We should update the pygraphviz gallery as well just in case some users aren't looking at the networkx gallery.

Great idea, 384dfc7..916f528 convert the existing `examples.rst` to a sphinx-gallery using the new image scraper. Here's what it would look like: https://rossbar.github.io/pygraphviz/auto_examples/index.html.

I elected not to include the `django_simple.py` and `utf8_encoding.py` examples in the gallery for now - it's probably worth reviewing how valuable they are overall (they've been renamed with `skip_` prefixes, which I've configured `sphinx-gallery` to ignore).

**Comment by rossbar** [comment]
With the addition of `sphinx-gallery` to the pygraphviz docs, I'm going to mark this as ready to review. There are still a few outstanding questions; a few the come to mind are:
 - where should the image scraper live? I chose `pygraphviz.scrapers` arbitrarily - maybe a more descriptive name or a subpackage would be better? I'll take a look at how `PyVista` did it
 - Similar, what it should be called (`PNGScraper` was the name given in the `sphinx-gallery` example that I derived this from)
 - A better way to handle dependencies: as currently structured, this adds at least `sphinx-gallery` and `matplotlib` as dependencies for pygraphviz. Maybe this is okay, or we can figure out a way to structure it so that the `scrapers` module is optional and only available if the other dependencies are installed.

There are other potential improvements (adding support for `.dot` files, adding a hook to [make the scraper easier to register with sphinx-gallery](https://sphinx-gallery.github.io/stable/advanced.html#integrate-custom-scrapers-with-sphinx-gallery)) but I'd prefer to leave them to follow-up PRs to keep this from getting too unwieldy.

**Review by jarrodmillman — APPROVED** [review]
Let's merge and improve in subsequent PRs.

**Pull request merged**
