### PR TITLE
WIP: Test on Python 3.7

### PR DESCRIPTION
**Pull request by jarrodmillman**
See networkx/networkx#3056

Xenial is not officially supported yet.

See travis-ci/travis-ci#9815

### CODE REVIEW

**Comment by dschult** [comment]
OK... This seems to pass the python 3.7 tests now.
It was all about StopIteration and being more explicit about how to handle that event.

**Comment by jarrodmillman** [comment]
@dschult We are still getting an error in the networkx tests:
```
test_agraph.TestAGraph.test_directed ... ok
test_agraph.TestAGraph.test_from_agraph_name ... ok
test_agraph.TestAGraph.test_graph_with_reserved_keywords ... ok
test_agraph.TestAGraph.test_multi_directed ... ok
test_agraph.TestAGraph.test_multi_undirected ... ok
test_agraph.TestAGraph.test_round_trip ... ok
test_agraph.TestAGraph.test_undirected ... ok
test_agraph.TestAGraph.test_view_pygraphviz ... Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/run-mailcap line 528.
Error: no "view" rule for type "image/png" passed its test case
       (for more information, add "--debug=1" on the command line)
[?1049h[H[2J[40;1HHit[Cany[Ckey[Cto[Cquit[Cw3m:[40;25H

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

I changed the pygraphviz line in the requirements file to
```
 git+https://github.com/jarrodmillman/pygraphviz@py37 
```
and reran the tests
```
https://travis-ci.org/networkx/networkx/builds/411808235
```
This fixed all the errors (we were getting) on Python 3.7 except the final one
```
test_agraph.TestAGraph.test_view_pygraphviz ... Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/run-mailcap line 528.
Error: no "view" rule for type "image/png" passed its test case
       (for more information, add "--debug=1" on the command line)
```

**Comment by dschult** [comment]
I'm not sure what the error message means on that last error...  but that is where I get lots of warning messages from fontconfig when I run the tests on my machine.

Also, the Travis-CI log seems to indicate that it hangs at that point in the tests and never continues to the next test: test_agraph.TestAGraph.test_view_pygraphviz_edgelabel

Any ideas on why it would hang at that point? It seems to be wanting to "view" the picture instead of writing it to a file.

**Comment by jarrodmillman** [comment]
This last error looks like it was an issue with xdg-open on xenial.  Here is someone talking about a similar problem:  https://askubuntu.com/questions/779717/xdg-open-stopped-working-since-16-04-upgrade

I will fix this in networkx.

**Comment by jarrodmillman** [comment]
This seems to supercede #146.

**Pull request merged**
